In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
import seaborn as sns


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/credit_card.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (2,5,12,13,14,15,19,20,21,22) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [ ]:
df.drop(['first','cc_num','trans_num','last','Unnamed: 0','lat', 'long','merch_lat','job','dob','trans_date_trans_time','city','merch_long','zip','street','city_pop','unix_time'],axis=1,inplace=True)

In [ ]:
df.columns

Index(['merchant', 'category', 'amt', 'gender', 'state', 'is_fraud'], dtype='object')

In [ ]:
df.dtypes

merchant    object
category    object
amt         object
gender      object
state       object
is_fraud    object
dtype: object

In [ ]:
df = df.drop(df.index[[555719]], axis = 0)  # Rows indicies to drop
#df['cc_num'] = pd.to_numeric(df['cc_num'])
df['is_fraud'] = df['is_fraud'].astype(int)
df['amt'] = df.amt.astype(float)
df.dtypes


merchant     object
category     object
amt         float64
gender       object
state        object
is_fraud      int64
dtype: object

In [ ]:
df['is_fraud'].value_counts()

0    1842743
1       9651
Name: is_fraud, dtype: int64

In [ ]:
shuffled_df = df.sample(frac=1,random_state=4)

# Put all the fraud class in a separate dataset.
fraud_df = shuffled_df.loc[shuffled_df['is_fraud'] == 1]

#Randomly select 9651 observations from the non-fraud (majority class)
non_fraud_df = shuffled_df.loc[shuffled_df['is_fraud'] == 0].sample(n=9651,random_state=42)

# Concatenate both dataframes again
normalized_df = pd.concat([fraud_df, non_fraud_df])


In [ ]:
normalized_df.reset_index(inplace=True)
df = normalized_df.iloc[:,1:]
df

merchant       category  ...  state is_fraud
0                       fraud_Lynch-Wisozk           home  ...     OK        1
1                       fraud_Kris-Padberg   shopping_pos  ...     OK        1
2      fraud_Baumbach, Strosin and Nicolas   shopping_pos  ...     CA        1
3                         fraud_Zulauf LLC  personal_care  ...     TX        1
4                    fraud_Rowe-Vandervort    grocery_net  ...     IN        1
...                                    ...            ...  ...    ...      ...
19297                  fraud_Schmeler-Howe  personal_care  ...     MD        0
19298              fraud_Reynolds-Schinner       misc_pos  ...     KY        0
19299  fraud_Schneider, Hayes and Nikolaus    food_dining  ...     IL        0
19300                    fraud_Block-Hauck         travel  ...     MI        0
19301   fraud_Gutmann, McLaughlin and Wiza           home  ...     KS        0

[19302 rows x 6 columns]

In [ ]:
df_api=df

In [ ]:
df_api

merchant       category  ...  state is_fraud
0                       fraud_Lynch-Wisozk           home  ...     OK        1
1                       fraud_Kris-Padberg   shopping_pos  ...     OK        1
2      fraud_Baumbach, Strosin and Nicolas   shopping_pos  ...     CA        1
3                         fraud_Zulauf LLC  personal_care  ...     TX        1
4                    fraud_Rowe-Vandervort    grocery_net  ...     IN        1
...                                    ...            ...  ...    ...      ...
19297                  fraud_Schmeler-Howe  personal_care  ...     MD        0
19298              fraud_Reynolds-Schinner       misc_pos  ...     KY        0
19299  fraud_Schneider, Hayes and Nikolaus    food_dining  ...     IL        0
19300                    fraud_Block-Hauck         travel  ...     MI        0
19301   fraud_Gutmann, McLaughlin and Wiza           home  ...     KS        0

[19302 rows x 6 columns]

In [ ]:
df['gender']=df['gender'].map(lambda a : 0 if a == 'M' else 1)
## Male is 0 F is 1


In [ ]:
df.nunique()

merchant      693
category       14
amt         13963
gender          2
state          51
is_fraud        2
dtype: int64

In [ ]:
df

merchant       category  ...  state  is_fraud
0                       fraud_Lynch-Wisozk           home  ...     OK         1
1                       fraud_Kris-Padberg   shopping_pos  ...     OK         1
2      fraud_Baumbach, Strosin and Nicolas   shopping_pos  ...     CA         1
3                         fraud_Zulauf LLC  personal_care  ...     TX         1
4                    fraud_Rowe-Vandervort    grocery_net  ...     IN         1
...                                    ...            ...  ...    ...       ...
19297                  fraud_Schmeler-Howe  personal_care  ...     MD         0
19298              fraud_Reynolds-Schinner       misc_pos  ...     KY         0
19299  fraud_Schneider, Hayes and Nikolaus    food_dining  ...     IL         0
19300                    fraud_Block-Hauck         travel  ...     MI         0
19301   fraud_Gutmann, McLaughlin and Wiza           home  ...     KS         0

[19302 rows x 6 columns]

In [ ]:
#df_api=df

In [ ]:
#df_api

merchant       category  ...  state  is_fraud
0                       fraud_Lynch-Wisozk           home  ...     OK         1
1                       fraud_Kris-Padberg   shopping_pos  ...     OK         1
2      fraud_Baumbach, Strosin and Nicolas   shopping_pos  ...     CA         1
3                         fraud_Zulauf LLC  personal_care  ...     TX         1
4                    fraud_Rowe-Vandervort    grocery_net  ...     IN         1
...                                    ...            ...  ...    ...       ...
19297                  fraud_Schmeler-Howe  personal_care  ...     MD         0
19298              fraud_Reynolds-Schinner       misc_pos  ...     KY         0
19299  fraud_Schneider, Hayes and Nikolaus    food_dining  ...     IL         0
19300                    fraud_Block-Hauck         travel  ...     MI         0
19301   fraud_Gutmann, McLaughlin and Wiza           home  ...     KS         0

[19302 rows x 6 columns]

In [ ]:
df.describe()

amt        gender      is_fraud
count  19302.000000  19302.000000  19302.000000
mean     298.939574      0.526785      0.500000
std      371.766175      0.499295      0.500013
min        1.010000      0.000000      0.000000
25%       20.630000      0.000000      0.000000
50%       87.490000      1.000000      0.500000
75%      473.845000      1.000000      1.000000
max     4399.610000      1.000000      1.000000

In [ ]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values


In [ ]:
state=pd.get_dummies(df.state)
merged=pd.concat([df,state],axis='columns')
df=merged.drop(['state','OK'],axis=1)

In [ ]:
category=pd.get_dummies(df.category)
merged=pd.concat([df,category],axis='columns')
df=merged.drop(['category','home'],axis=1)
df.shape

(19302, 67)

In [ ]:
df['merchant'] = df['merchant'].astype(str)
df.dtypes

merchant          object
amt              float64
gender             int64
is_fraud           int64
AK                 uint8
                  ...   
misc_pos           uint8
personal_care      uint8
shopping_net       uint8
shopping_pos       uint8
travel             uint8
Length: 67, dtype: object

In [ ]:
df.merchant.value_counts().sort_values(ascending= False).head(60)

fraud_Kilback LLC                             90
fraud_Boyer PLC                               85
fraud_Cormier LLC                             82
fraud_Rau and Sons                            82
fraud_Schultz, Simonis and Little             80
fraud_Romaguera, Cruickshank and Greenholt    78
fraud_Doyle Ltd                               77
fraud_Kuhn LLC                                76
fraud_Terry-Huel                              75
fraud_Kozey-Boehm                             75
fraud_Huel, Hammes and Witting                73
fraud_Heathcote, Yost and Kertzmann           72
fraud_Strosin-Cruickshank                     71
fraud_Goldner, Kovacek and Abbott             71
fraud_Stracke-Lemke                           71
fraud_Koepp-Witting                           70
fraud_Moen, Reinger and Murphy                70
fraud_Kiehn-Emmerich                          69
fraud_Boyer-Reichert                          69
fraud_Padberg-Welch                           68
fraud_Schmeler, Bash

In [ ]:
top_60= [x for x in df.merchant.value_counts().sort_values(ascending= False).head(60).index]

In [ ]:
for label in top_60:
  df[label] = np.where(df['merchant']==label,1,0)

In [ ]:
df.shape

(19302, 127)

In [ ]:
df.drop(['merchant'],axis=1,inplace=True)

In [ ]:
df

amt  gender  ...  fraud_Deckow-O'Conner  fraud_Schmidt and Sons
0      290.62       1  ...                      0                       0
1      841.98       0  ...                      0                       0
2      932.02       1  ...                      0                       0
3       18.60       0  ...                      0                       0
4       12.55       1  ...                      0                       0
...       ...     ...  ...                    ...                     ...
19297   67.86       0  ...                      0                       0
19298    1.44       1  ...                      0                       0
19299    1.45       1  ...                      0                       0
19300    2.01       0  ...                      0                       0
19301   28.20       0  ...                      0                       0

[19302 rows x 126 columns]

In [ ]:
col = df.pop('is_fraud')
df.insert(125,'is_fraud',col,allow_duplicates=False)
df

amt  gender  ...  fraud_Schmidt and Sons  is_fraud
0      290.62       1  ...                       0         1
1      841.98       0  ...                       0         1
2      932.02       1  ...                       0         1
3       18.60       0  ...                       0         1
4       12.55       1  ...                       0         1
...       ...     ...  ...                     ...       ...
19297   67.86       0  ...                       0         0
19298    1.44       1  ...                       0         0
19299    1.45       1  ...                       0         0
19300    2.01       0  ...                       0         0
19301   28.20       0  ...                       0         0

[19302 rows x 126 columns]

In [ ]:
#from sklearn.preprocessing import minmax_scale
#df[['amt']] = minmax_scale(df[['amt']])

In [ ]:
#df

# **TRAIN & Split**

In [ ]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [ ]:
from  sklearn.model_selection import train_test_split
x_train ,x_test , y_train, y_test = train_test_split (x,y,test_size=0.2,random_state=1)

In [ ]:
print(x_train)

[[311.93   0.     0.   ...   0.     0.     0.  ]
 [434.66   1.     0.   ...   0.     0.     0.  ]
 [ 10.23   1.     0.   ...   0.     0.     0.  ]
 ...
 [933.06   0.     0.   ...   0.     0.     0.  ]
 [ 92.1    1.     0.   ...   0.     0.     0.  ]
 [ 10.92   1.     0.   ...   0.     0.     0.  ]]


In [ ]:
print(y_train)

[1 1 1 ... 1 0 1]


# **Feature Scaling**

In [ ]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x_train[:,0:1]= sc.fit_transform(x_train[:,0:1])
x_test[:,0:1]= sc.transform(x_test[:,0:1])

In [ ]:
x_train.shape

(15441, 125)

# **SVM**

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(x_train, y_train)

SVC(kernel='linear', random_state=0)

In [ ]:
y_pred = classifier.predict(x_test)


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1818   72]
 [ 464 1507]]


0.8611758611758612

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.80      0.96      0.87      1890
           1       0.95      0.76      0.85      1971

    accuracy                           0.86      3861
   macro avg       0.88      0.86      0.86      3861
weighted avg       0.88      0.86      0.86      3861



# **Decision Tree**

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [ ]:
y_pred = classifier.predict(x_test)


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1798   92]
 [  90 1881]]


0.9528619528619529

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.95      0.95      0.95      1890
           1       0.95      0.95      0.95      1971

    accuracy                           0.95      3861
   macro avg       0.95      0.95      0.95      3861
weighted avg       0.95      0.95      0.95      3861



# **Random Forest**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [ ]:
y_pred = classifier.predict(x_test)

In [ ]:
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 ...
 [1 1]
 [1 1]
 [1 1]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1797   93]
 [ 117 1854]]


0.9456099456099456

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.95      0.94      1890
           1       0.95      0.94      0.95      1971

    accuracy                           0.95      3861
   macro avg       0.95      0.95      0.95      3861
weighted avg       0.95      0.95      0.95      3861



Kernel PCA

In [ ]:
from sklearn.decomposition import KernelPCA
kpca = KernelPCA(n_components = 2, kernel = 'rbf')
x_train_kpca = kpca.fit_transform(x_train)
x_test_kpca = kpca.transform(x_test)

# **Naive Bayes**

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train_kpca, y_train)

GaussianNB()

In [ ]:
y_pred = classifier.predict(x_test_kpca)
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1842   48]
 [ 546 1425]]


0.8461538461538461

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.77      0.97      0.86      1890
           1       0.97      0.72      0.83      1971

    accuracy                           0.85      3861
   macro avg       0.87      0.85      0.84      3861
weighted avg       0.87      0.85      0.84      3861



# **KNN**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(x_train_kpca, y_train)

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(x_test_kpca)


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1705  185]
 [ 180 1791]]


0.9054649054649054

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.90      0.90      0.90      1890
           1       0.91      0.91      0.91      1971

    accuracy                           0.91      3861
   macro avg       0.91      0.91      0.91      3861
weighted avg       0.91      0.91      0.91      3861



# **Logistic Regression**

In [ ]:
from sklearn.linear_model import LogisticRegression
regressor = LogisticRegression(random_state = 0)
regressor.fit(x_train_kpca,y_train)


LogisticRegression(random_state=0)

In [ ]:
y_pred = regressor.predict(x_test_kpca)
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1817   73]
 [ 471 1500]]


0.8591038591038591

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.79      0.96      0.87      1890
           1       0.95      0.76      0.85      1971

    accuracy                           0.86      3861
   macro avg       0.87      0.86      0.86      3861
weighted avg       0.88      0.86      0.86      3861



# **XGBOOST**

In [ ]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(x_train, y_train)

XGBClassifier()

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(x_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1812   78]
 [ 125 1846]]


0.9474229474229474

In [ ]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = x_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 94.91 %
Standard Deviation: 0.62 %


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.96      0.95      1890
           1       0.96      0.94      0.95      1971

    accuracy                           0.95      3861
   macro avg       0.95      0.95      0.95      3861
weighted avg       0.95      0.95      0.95      3861



# **Deep Learning**

**ANN**

In [ ]:
import tensorflow as tf

In [ ]:
ann = tf.keras.models.Sequential()

In [ ]:
ann.add(tf.keras.layers.Dense(units=40, activation='sigmoid'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=40, activation='sigmoid'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=40, activation='sigmoid'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=40, activation='sigmoid'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=40, activation='sigmoid'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=40, activation='sigmoid'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=40, activation='sigmoid'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [ ]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 400)

Epoch 1/400
483/483 [==============================] - 2s 3ms/step - loss: 0.6136 - accuracy: 0.6151
Epoch 2/400
483/483 [==============================] - 1s 3ms/step - loss: 0.3616 - accuracy: 0.8582
Epoch 3/400
483/483 [==============================] - 1s 2ms/step - loss: 0.3548 - accuracy: 0.8599
Epoch 4/400
483/483 [==============================] - 1s 2ms/step - loss: 0.3517 - accuracy: 0.8608
Epoch 5/400
483/483 [==============================] - 1s 2ms/step - loss: 0.3478 - accuracy: 0.8617
Epoch 6/400
483/483 [==============================] - 1s 2ms/step - loss: 0.3472 - accuracy: 0.8617
Epoch 7/400
483/483 [==============================] - 1s 2ms/step - loss: 0.3460 - accuracy: 0.8623
Epoch 8/400
483/483 [==============================] - 1s 2ms/step - loss: 0.3470 - accuracy: 0.8617
Epoch 9/400
483/483 [==============================] - 1s 2ms/step - loss: 0.3459 - accuracy: 0.8626
Epoch 10/400
483/483 [==============================] - 1s 2ms/step - loss: 0.3459 - accura

In [ ]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 ...
 [1 1]
 [1 1]
 [1 1]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1819   71]
 [ 206 1765]]


0.9282569282569283

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.90      0.96      0.93      1890
           1       0.96      0.90      0.93      1971

    accuracy                           0.93      3861
   macro avg       0.93      0.93      0.93      3861
weighted avg       0.93      0.93      0.93      3861



# **Apriori**

In [ ]:
!pip install apyori
from apyori import apriori

  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5974 sha256=abcf545a24ca3d311463ea1670ca5464fb5b8fd63684b3c60bbeac88cee4c9ab
  Stored in directory: /root/.cache/pip/wheels/cb/f6/e1/57973c631d27efd1a2f375bd6a83b2a616c4021f24aab84080
Successfully built apyori


In [ ]:
df_api
transactions_api=[]
for i in range(0, 19302):
  transactions_api.append([str(df_api.values[i,j]) for j in range(0, 6)])

In [ ]:
rules = apriori(transactions = transactions_api, min_support = 0.003, min_confidence = 0.2, min_lift = 3, min_length = 2, max_length = 2)

In [ ]:
results = list(rules)

In [ ]:
results

[RelationRecord(items=frozenset({'fraud_Auer-Mosciski', 'grocery_pos'}), support=0.00305667806444928, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fraud_Auer-Mosciski'}), items_add=frozenset({'grocery_pos'}), confidence=1.0, lift=6.135410044500953)]),
 RelationRecord(items=frozenset({'fraud_Bailey-Morar', 'grocery_pos'}), support=0.003108486167236556, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fraud_Bailey-Morar'}), items_add=frozenset({'grocery_pos'}), confidence=1.0, lift=6.135410044500953)]),
 RelationRecord(items=frozenset({'shopping_net', 'fraud_Boyer PLC'}), support=0.0034193347839602114, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fraud_Boyer PLC'}), items_add=frozenset({'shopping_net'}), confidence=0.776470588235294, lift=5.087384689109859)]),
 RelationRecord(items=frozenset({'shopping_net', 'fraud_Boyer-Reichert'}), support=0.003574759092322039, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fraud_Boyer-Reichert'}), 

In [ ]:
def inspect(results):
    lhs         = [tuple(result[2][0][0])[0] for result in results]
    rhs         = [tuple(result[2][0][1])[0] for result in results]
    supports    = [result[1] for result in results]
    confidences = [result[2][0][2] for result in results]
    lifts       = [result[2][0][3] for result in results]
    return list(zip(lhs, rhs, supports, confidences, lifts))
resultsinDataFrame = pd.DataFrame(inspect(results), columns = ['Left Hand Side', 'Right Hand Side', 'Support', 'Confidence', 'Lift'])

In [ ]:
resultsinDataFrame

Left Hand Side Right Hand Side   Support  Confidence      Lift
0         fraud_Auer-Mosciski     grocery_pos  0.003057    1.000000  6.135410
1          fraud_Bailey-Morar     grocery_pos  0.003108    1.000000  6.135410
2             fraud_Boyer PLC    shopping_net  0.003419    0.776471  5.087385
3        fraud_Boyer-Reichert    shopping_net  0.003575    1.000000  6.551935
4           fraud_Bradtke PLC     grocery_pos  0.003160    1.000000  6.135410
..                        ...             ...       ...         ...       ...
61        fraud_Stracke-Lemke     grocery_pos  0.003678    1.000000  6.135410
62  fraud_Strosin-Cruickshank     grocery_pos  0.003678    1.000000  6.135410
63           fraud_Terry-Huel    shopping_net  0.003886    1.000000  6.551935
64      fraud_Vandervort-Funk     grocery_pos  0.003523    1.000000  6.135410
65             fraud_Wolf Inc     grocery_pos  0.003212    1.000000  6.135410

[66 rows x 5 columns]